<div class="feuillePerso">
    <h2>{{$personage->prenom}} {{$personage->nom}}</h2>
    <ul>
        @component('contenu.fichePersoLigne')
            @slot('titre')
                Espèce
            @endslot
            @slot('info')
                {{$personage->espece}}
            @endslot
        @endcomponent
        @component('contenu.fichePersoLigne')
            @slot('titre')
                Race
            @endslot
            @slot('info')
                {{$personage->race}}
            @endslot
        @endcomponent
        @component('contenu.fichePersoLigne')
            @slot('titre')
                Sexe
            @endslot
            @slot('info')
                {{$personage->sexe}}
            @endslot
        @endcomponent
        @component('contenu.fichePersoLigne')
            @slot('titre')
                Age
            @endslot
            @slot('info')
                {{$personage->age}}
            @endslot
        @endcomponent
        @component('contenu.fichePersoLigne')
            @slot('titre')
                Periode d'age
            @endslot
            @slot('info')
                {{$personage->ageType}}
            @endslot
        @endcomponent
        @component('contenu.fichePersoLigne')
            @slot('titre')
                Taille
            @endslot
            @slot('info')
                {{$personage->cadre}}
            @endslot
        @endcomponent
    </ul>
    {{$personage}}
</div>